In [1]:
import pandas as pd
df=pd.read_csv('train.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [2]:
features = ["Pclass", "Sex", "Age", "SibSp", "Parch", "Fare", "Embarked"]
target = "Survived"

df1=df[features+[target]]
df1.head()

   Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Survived
0       3    male  22.0      1      0   7.2500        S         0
1       1  female  38.0      1      0  71.2833        C         1
2       3  female  26.0      0      0   7.9250        S         1
3       1  female  35.0      1      0  53.1000        S         1
4       3    male  35.0      0      0   8.0500        S         0

In [3]:
df1.isna().sum()

Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
Survived      0
dtype: int64

In [4]:
df1['Age']=df1['Age'].fillna(df['Age'].median())
df1.isna().sum()

C:\Users\Sahil sharma\AppData\Local\Temp\ipykernel_15068\4144223162.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Age']=df1['Age'].fillna(df['Age'].median())

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
Survived    0
dtype: int64

In [5]:
df1['Embarked']=df1['Embarked'].fillna(df1['Embarked'].mode()[0])
df1.isna().sum()

C:\Users\Sahil sharma\AppData\Local\Temp\ipykernel_15068\2994186866.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Embarked']=df1['Embarked'].fillna(df1['Embarked'].mode()[0])

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Survived    0
dtype: int64

In [6]:
df1['Sex']=df1['Sex'].map({'male':0,'female':1})
df1=pd.get_dummies(df1,columns=['Embarked'],drop_first=True)
df1.head()

C:\Users\Sahil sharma\AppData\Local\Temp\ipykernel_15068\245065638.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1['Sex']=df1['Sex'].map({'male':0,'female':1})

   Pclass  Sex   Age  SibSp  Parch     Fare  Survived  Embarked_Q  Embarked_S
0       3    0  22.0      1      0   7.2500         0       False        True
1       1    1  38.0      1      0  71.2833         1       False       False
2       3    1  26.0      0      0   7.9250         1       False        True
3       1    1  35.0      1      0  53.1000         1       False        True
4       3    0  35.0      0      0   8.0500         0       False        True

In [7]:
X=df1.drop("Survived",axis=1)
y=df1["Survived"]
print(X.shape,y.shape)

(891, 8) (891,)

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [10]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

dt=DecisionTreeClassifier(max_depth=3,random_state=42)
dt.fit(X_train,y_train)

dt_pred=dt.predict(X_test)
print("Accuracy score =",accuracy_score(y_test,dt_pred))

Accuracy score = 0.7932960893854749

In [11]:
from sklearn.ensemble import RandomForestClassifier

rf=RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    n_jobs=-1,
    max_depth=3
)

rf.fit(X_train,y_train)
rf_predict=rf.predict(X_test)

print("Accuracy score =",accuracy_score(y_test,rf_predict))

Accuracy score = 0.8100558659217877

In [12]:
feature_importance = pd.Series(
    rf.feature_importances_,
    index=X.columns
).sort_values(ascending=False)

feature_importance

Sex           0.522296
Fare          0.191217
Pclass        0.117813
Age           0.074312
Embarked_S    0.030883
Parch         0.028527
SibSp         0.024645
Embarked_Q    0.010306
dtype: float64